/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface TokenFactoryInterface extends Interface {
    getFunction(nameOrSignature: "allTokens" | "createStandardToken" | "creationFee" | "feeReceiver" | "getAllTokensCount" | "getUserTokens" | "owner" | "renounceOwnership" | "soltToken" | "transferOwnership" | "updateFee" | "updateFeeReceiver" | "userTokens"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "TokenCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'allTokens', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createStandardToken', values: [string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'creationFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeReceiver', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllTokensCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getUserTokens', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'soltToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateFeeReceiver', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userTokens', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'allTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createStandardToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creationFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeReceiver', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllTokensCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'soltToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateFeeReceiver', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userTokens', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenCreatedEvent {
      export type InputTuple = [tokenAddress: AddressLike, creator: AddressLike, name: string, symbol: string, supply: BigNumberish, decimals: BigNumberish];
      export type OutputTuple = [tokenAddress: string, creator: string, name: string, symbol: string, supply: bigint, decimals: bigint];
      export interface OutputObject {tokenAddress: string, creator: string, name: string, symbol: string, supply: bigint, decimals: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TokenFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): TokenFactory;
    waitForDeployment(): Promise<this>;

    interface: TokenFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    allTokens: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    createStandardToken: TypedContractMethod<
      [name: string, symbol: string, supply: BigNumberish, decimalsValue: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    creationFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feeReceiver: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAllTokensCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getUserTokens: TypedContractMethod<
      [user: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    soltToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateFee: TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateFeeReceiver: TypedContractMethod<
      [_newReceiver: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    userTokens: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'allTokens'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createStandardToken'): TypedContractMethod<
      [name: string, symbol: string, supply: BigNumberish, decimalsValue: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'creationFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeReceiver'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAllTokensCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserTokens'): TypedContractMethod<
      [user: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'soltToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateFee'): TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateFeeReceiver'): TypedContractMethod<
      [_newReceiver: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userTokens'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TokenCreated'): TypedContractEvent<TokenCreatedEvent.InputTuple, TokenCreatedEvent.OutputTuple, TokenCreatedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TokenCreated(address,address,string,string,uint256,uint8)': TypedContractEvent<TokenCreatedEvent.InputTuple, TokenCreatedEvent.OutputTuple, TokenCreatedEvent.OutputObject>;
      TokenCreated: TypedContractEvent<TokenCreatedEvent.InputTuple, TokenCreatedEvent.OutputTuple, TokenCreatedEvent.OutputObject>;
    
    };
  }